# -*- coding: utf-8 -*-
"""Copy of Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGwS9dKBeciwndH1XNtD96W5DFYv4yeQ
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Split this string"""

s = "Hi there Sam!"

x=s.split()
print(x)

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

"""# Basic Python"""

x="The diameter of {planet} is {diameter} kilometers.".format(planet = "Earth" ,diameter =12742)
print(x)

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]['tricky'][3]['target'][3])

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

arr=np.zeros(10)
arr

arr=np.ones(10)*5
arr

"""## 5. Create an array of all the even integers from 20 to 35"""

arr=np.arange(20,35,2)
arr

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

arr = np.arange(0,9).reshape(3,3)
arr

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a=np.array([1,2,3])
b=np.array([4,5,6])
c = np.concatenate((a, b)) 
c

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

d={"Name":["Gopal","sai","shiv"],"age":[26,56,45]}
df=pd.DataFrame(d)
df.iloc[0:3,0:2]

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import pandas as pd
from datetime import date

pd.date_range(start="2023-01-01",end="2023-02-10").to_pydatetime().tolist()



"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df=pd.DataFrame(lists)
df